[package]
name = "variable_enum_macro"
version = "0.4.0-beta"
edition = "2021"

[dependencies]
var_provider = { path=".." }
proc-macro2 = "1.0.79"
quote = "1.0.36"
itertools = "0.12"
syn = { version = "2.0.58" }
strum = "0.26.2"
strum_macros = "0.26.2"

[lib]
proc-macro = true
