name: Run tests

on:
  pull_request:
  push:
    branches:
      - main

# Make sure CI fails on all warnings, including Clippy lints
# env:
#   RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, osx, win-msvc, win-gnu]
        include:
        - build: linux
          os: ubuntu-latest
          rust: stable
        - build: osx
          os: macos-latest
          rust: stable
        - build: win-msvc
          os: windows-latest
          rust: stable
        - build: win-gnu
          os: windows-latest
          rust: stable-x86_64-gnu
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
    - run: cargo clean
    - run: cargo build --verbose --jobs 1
      env:
        CARGO_INCREMENTAL: 0
        RUSTFLAGS: "-C debuginfo=0"
    - run: cargo test --verbose
