name: Build release binary

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  create-release:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            rust: stable
          - build: macos-aarch64
            os: macos-latest
            target: aarch64-apple-darwin
            rust: stable
          - build: macos-x86_64
            os: macos-latest
            target: x86_64-apple-darwin
            rust: stable
          - build: windows-msvc
            os: windows-latest
            target: x86_64-pc-windows-msvc
            rust: stable

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get the release version from the tag
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}

      - name: Build binary
        run: cargo build --release --verbose --target ${{ matrix.target }}

      - name: Build archive
        shell: bash
        run: |
          bin=st

          name="$bin-${{ env.VERSION }}-${{ matrix.target }}"
          mkdir "$name"
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv "target/${{ matrix.target }}/release/$bin.exe" "$name"
          else
            mv "target/${{ matrix.target }}/release/$bin" "$name"
          fi

          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            7z a "$name.zip" "$name"
            echo "ASSET=$name.zip" >> $GITHUB_ENV
          else
            tar -czf "$name.tar.gz" "$name"
            echo "ASSET=$name.tar.gz" >> $GITHUB_ENV
          fi

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.ASSET }}
    